import { CommonModule } from '@angular/common';
import { Component, inject, OnDestroy, OnInit } from '@angular/core';
import { FormArray, FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { debounceTime, distinctUntilChanged, finalize, forkJoin, of, Subject, switchMap, takeUntil } from 'rxjs';
import { apiMessage } from '../core/auth';
import { AdminCategoryService, AdminProductService } from '../core/api';
import { Category, Page, Product, ProductRequest, ProductVariant, ProductVariantRequest } from '../core/models';

@Component({
  selector: 'app-products-page', standalone: true, imports: [CommonModule, ReactiveFormsModule, RouterLink],
  template: `
    <header class="admin-page-head"><div><span class="kicker">CATALOG</span><h1>Products</h1><p>Manage the pastries currently visible to customers.</p></div><a class="admin-primary" routerLink="/products/new">Add product</a></header>
    <p class="contract-note">The backend currently exposes only active public products for reading. Deactivated products disappear from this workspace until an admin read endpoint is added.</p>
    <section class="toolbar"><label class="search-field"><span>⌕</span><input [formControl]="search" placeholder="Search name or description"></label><label><span>Category</span><select [formControl]="category"><option value="">All categories</option><option *ngFor="let item of categories" [value]="item.id">{{ item.name }}</option></select></label></section>
    <p class="alert" role="alert" aria-live="assertive" *ngIf="error">{{ error }} <button type="button" (click)="load()">Retry</button></p>
    <section class="admin-panel flush"><p class="loading-state" *ngIf="loading">Loading active catalog…</p><div class="empty-state" *ngIf="!loading && !page?.content?.length"><strong>No products found</strong><span>Try a different search or add a new product.</span></div>
      <div class="table-wrap" *ngIf="page?.content?.length"><table class="product-table"><thead><tr><th scope="col">Product</th><th scope="col">Category</th><th scope="col">Variants</th><th scope="col">From</th><th scope="col">Status</th><th scope="col"><span class="visually-hidden">Actions</span></th></tr></thead><tbody><tr *ngFor="let product of page?.content"><td><div class="product-cell"><img [src]="product.imageUrl" [alt]="product.name + ' product image'" (error)="useFallback($event)"><div><strong>{{ product.name }}</strong><small>{{ product.description || 'No description' }}</small></div></div></td><td>{{ product.categoryName }}</td><td>{{ activeVariants(product) }} active</td><td>{{ minimumPrice(product) | currency:'INR':'symbol':'1.0-0' }}</td><td><span class="status-pill" data-status="ACTIVE">Active</span></td><td><div class="row-menu"><a [routerLink]="['/products', product.id, 'edit']">Edit</a><button class="danger" type="button" (click)="pendingDeactivate = product">Deactivate</button></div></td></tr></tbody></table></div>
      <div class="pager" *ngIf="page && page.totalPages > 1"><span>Showing {{ page.number * page.size + 1 }}–{{ page.number * page.size + page.content.length }} of {{ page.totalElements }}</span><button type="button" aria-label="Previous products page" [disabled]="page.first" (click)="go(page.number - 1)">Previous</button><span>Page {{ page.number + 1 }} of {{ page.totalPages }}</span><button type="button" aria-label="Next products page" [disabled]="page.last" (click)="go(page.number + 1)">Next</button></div>
    </section><div class="modal-backdrop" *ngIf="pendingDeactivate" (click)="pendingDeactivate = null"><section class="admin-modal confirm-modal" role="alertdialog" aria-modal="true" aria-labelledby="deactivate-product-title" (click)="$event.stopPropagation()"><span class="kicker">DEACTIVATE PRODUCT</span><h2 id="deactivate-product-title">Remove {{ pendingDeactivate.name }} from the catalog?</h2><p>The product and its variants will disappear from the customer store. The current backend does not provide an admin view for restoring inactive products.</p><div class="modal-actions"><button class="admin-secondary" type="button" (click)="pendingDeactivate = null">Keep active</button><button class="admin-primary destructive" type="button" (click)="confirmDeactivate()">Deactivate product</button></div></section></div>`
})
export class AdminProductsPage implements OnInit, OnDestroy {
  private readonly api = inject(AdminProductService); private readonly categoryApi = inject(AdminCategoryService); private readonly fb = inject(FormBuilder); private readonly destroy$ = new Subject<void>();
  readonly search = this.fb.nonNullable.control(''); readonly category = this.fb.nonNullable.control('');
  categories: Category[] = []; page: Page<Product> | null = null; pendingDeactivate: Product | null = null; currentPage = 0; loading = true; error = '';
  ngOnInit(): void { this.categoryApi.listVisible().subscribe({ next: (items) => this.categories = items }); this.search.valueChanges.pipe(debounceTime(350), distinctUntilChanged(), takeUntil(this.destroy$)).subscribe(() => { this.currentPage = 0; this.load(); }); this.category.valueChanges.pipe(takeUntil(this.destroy$)).subscribe(() => { this.currentPage = 0; this.load(); }); this.load(); }
  ngOnDestroy(): void { this.destroy$.next(); this.destroy$.complete(); }
  load(): void { this.loading = true; this.error = ''; const categoryId = Number(this.category.value) || undefined; this.api.listVisible(this.currentPage, 12, this.search.value, categoryId).pipe(finalize(() => this.loading = false)).subscribe({ next: (page) => this.page = page, error: (error: unknown) => this.error = apiMessage(error, 'Unable to load products.') }); }
  go(page: number): void { this.currentPage = page; this.load(); }
  activeVariants(product: Product): number { return product.variants.filter((item) => item.active).length; }
  minimumPrice(product: Product): number | null { const prices = product.variants.filter((item) => item.active).map((item) => item.price); return prices.length ? Math.min(...prices) : null; }
  useFallback(event: Event): void { (event.target as HTMLImageElement).src = 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=240&q=75'; }
  confirmDeactivate(): void { if (!this.pendingDeactivate) return; this.api.setActive(this.pendingDeactivate.id, false).subscribe({ next: () => { this.pendingDeactivate = null; this.load(); }, error: (error: unknown) => this.error = apiMessage(error, 'Unable to deactivate product.') }); }
}

@Component({
  selector: 'app-product-form-page', standalone: true, imports: [CommonModule, ReactiveFormsModule, RouterLink],
  template: `
    <header class="admin-page-head compact"><div><a class="back-link" routerLink="/products">← Products</a><span class="kicker">{{ productId ? 'UPDATE PRODUCT' : 'NEW PRODUCT' }}</span><h1>{{ productId ? 'Edit product' : 'Create product' }}</h1><p>Product details and purchasable variants are saved to the backend separately.</p></div><button class="admin-primary desktop-save" type="button" [disabled]="form.invalid || saving" (click)="save()">{{ saving ? 'Saving…' : 'Save product' }}</button></header>
    <p class="alert" role="alert" aria-live="assertive" *ngIf="error">{{ error }}</p><p class="success-banner" role="status" aria-live="polite" *ngIf="message">{{ message }}</p><p class="loading-state" *ngIf="loading">Loading product editor…</p>
    <form class="editor-layout" [formGroup]="form" *ngIf="!loading" (ngSubmit)="save()"><div class="editor-main">
      <section class="form-panel"><div class="panel-title"><span>01</span><div><h2>Product information</h2><p>Customer-facing content and category placement.</p></div></div><p class="form-warning" *ngIf="!categories.length">Create an active category before saving a product.</p><div class="form-fields"><label>Product name<input formControlName="name" maxlength="200" placeholder="Chocolate celebration cake" [attr.aria-invalid]="form.controls.name.touched && form.controls.name.invalid"><small class="field-error" *ngIf="form.controls.name.touched && form.controls.name.invalid">Product name is required.</small></label><label>Description<textarea formControlName="description" maxlength="5000" rows="6" placeholder="Describe flavour, texture, and occasion…"></textarea></label><label>Category<select formControlName="categoryId" [attr.aria-invalid]="form.controls.categoryId.touched && form.controls.categoryId.invalid"><option [ngValue]="null" disabled>Select a category</option><option *ngFor="let item of categories" [ngValue]="item.id">{{ item.name }}</option></select><small class="field-error" *ngIf="form.controls.categoryId.touched && form.controls.categoryId.invalid">Choose a category.</small></label></div></section>
      <section class="form-panel"><div class="panel-title"><span>02</span><div><h2>Variants</h2><p>Each row is a purchasable weight, flavour, and egg preference.</p></div><button class="admin-secondary" type="button" (click)="addVariant()">Add variant</button></div><div class="variant-list" formArrayName="variants"><article *ngFor="let group of variantGroups; let index = index" [formGroupName]="index"><div class="variant-index">{{ index + 1 }}</div><label>Weight (g)<input type="number" min="1" formControlName="weightInGrams" placeholder="500"></label><label>Flavour<input formControlName="flavour" placeholder="Chocolate"></label><label>Egg type<select formControlName="eggType"><option value="">Not specified</option><option value="EGGLESS">Eggless</option><option value="EGG">With egg</option></select></label><label>Price ₹<input type="number" min="0.01" step="0.01" formControlName="price" [attr.aria-invalid]="group.controls['price'].touched && group.controls['price'].invalid"><small class="field-error" *ngIf="group.controls['price'].touched && group.controls['price'].invalid">Enter a price greater than zero.</small></label><div class="variant-actions"><span class="status-pill" [attr.data-status]="group.value.active ? 'ACTIVE' : 'INACTIVE'">{{ group.value.active ? 'Active' : 'Inactive' }}</span><button type="button" *ngIf="group.value.id" (click)="toggleVariant(group)">{{ group.value.active ? 'Deactivate' : 'Activate' }}</button><button class="danger" type="button" *ngIf="!group.value.id" (click)="removeVariant(index)">Remove</button></div></article></div></section>
    </div><aside class="editor-aside"><section class="form-panel image-panel"><div class="panel-title"><span>03</span><div><h2>Product image</h2><p>One image URL is supported.</p></div></div><div class="image-preview"><img *ngIf="form.value.imageUrl; else noImage" [src]="form.value.imageUrl" alt="Product preview"><ng-template #noImage><div><strong>No image yet</strong><span>Paste a direct image URL below.</span></div></ng-template></div><label>Image URL<input formControlName="imageUrl" maxlength="1000" placeholder="https://…" [attr.aria-invalid]="form.controls.imageUrl.touched && form.controls.imageUrl.invalid"><small class="field-error" *ngIf="form.controls.imageUrl.touched && form.controls.imageUrl.invalid">Enter a complete http or https image URL.</small></label></section><section class="form-panel publication"><h3>Publication</h3><p>New products and variants use backend defaults. Existing statuses can be changed from the catalog or variant controls.</p><div class="price-range" *ngIf="minimumVariantPrice !== null"><span>Variant price range</span><strong>{{ minimumVariantPrice | currency:'INR':'symbol':'1.0-0' }} – {{ maximumVariantPrice | currency:'INR':'symbol':'1.0-0' }}</strong></div><span class="status-pill" [attr.data-status]="product?.active ? 'ACTIVE' : 'DRAFT'">{{ productId ? (product?.active ? 'Active' : 'Inactive') : 'New' }}</span></section><button class="admin-primary mobile-save" type="submit" [disabled]="form.invalid || saving">{{ saving ? 'Saving…' : 'Save product' }}</button></aside></form>`
})
export class ProductFormPage implements OnInit {
  private readonly fb = inject(FormBuilder); private readonly api = inject(AdminProductService); private readonly categoriesApi = inject(AdminCategoryService); private readonly route = inject(ActivatedRoute); private readonly router = inject(Router);
  productId: number | null = null; product: Product | null = null; categories: Category[] = []; loading = true; saving = false; error = ''; message = '';
  readonly form = this.fb.group({ name: ['', [Validators.required, Validators.maxLength(200)]], description: ['', Validators.maxLength(5000)], categoryId: [null as number | null, Validators.required], imageUrl: ['', [Validators.required, Validators.maxLength(1000), Validators.pattern(/^https?:\/\/\S+$/i)]], variants: this.fb.array<FormGroup>([]) });
  get variants(): FormArray<FormGroup> { return this.form.controls.variants; }
  get variantGroups(): FormGroup[] { return this.variants.controls; }
  get minimumVariantPrice(): number | null { const prices = this.variantGroups.map((group) => Number(group.value.price)).filter((price) => price > 0); return prices.length ? Math.min(...prices) : null; }
  get maximumVariantPrice(): number | null { const prices = this.variantGroups.map((group) => Number(group.value.price)).filter((price) => price > 0); return prices.length ? Math.max(...prices) : null; }
  ngOnInit(): void { this.productId = Number(this.route.snapshot.paramMap.get('id')) || null; this.categoriesApi.listVisible().subscribe({ next: (items) => this.categories = items, error: (error: unknown) => this.error = apiMessage(error, 'Unable to load categories.') }); if (this.productId) { this.api.getVisible(this.productId).pipe(finalize(() => this.loading = false)).subscribe({ next: (product) => this.populate(product), error: (error: unknown) => this.error = apiMessage(error, 'Unable to load this product. Inactive products are not readable through the current backend API.') }); } else { this.addVariant(); this.loading = false; } }
  private variantGroup(variant?: ProductVariant): FormGroup { return this.fb.group({ id: [variant?.id || null], weightInGrams: [variant?.weightInGrams || null], flavour: [variant?.flavour || ''], eggType: [variant?.eggType || ''], price: [variant?.price || null, [Validators.required, Validators.min(0.01)]], active: [variant?.active ?? true] }); }
  private populate(product: Product): void { this.product = product; this.form.patchValue({ name: product.name, description: product.description || '', categoryId: product.categoryId, imageUrl: product.imageUrl }); product.variants.forEach((variant) => this.variants.push(this.variantGroup(variant))); if (!product.variants.length) this.addVariant(); }
  addVariant(): void { this.variants.push(this.variantGroup()); }
  removeVariant(index: number): void { if (this.variants.length > 1) this.variants.removeAt(index); }
  toVariantRequest(group: FormGroup): ProductVariantRequest { const value = group.getRawValue(); return { weightInGrams: value.weightInGrams ? Number(value.weightInGrams) : null, flavour: value.flavour || '', eggType: value.eggType || null, price: Number(value.price) }; }
  save(): void { if (this.form.invalid) { this.form.markAllAsTouched(); return; } this.saving = true; this.error = ''; this.message = ''; const value = this.form.getRawValue(); const productRequest: ProductRequest = { name: value.name || '', description: value.description || '', categoryId: Number(value.categoryId), imageUrl: value.imageUrl || '' }; const productRequest$ = this.productId ? this.api.update(this.productId, productRequest) : this.api.create(productRequest); productRequest$.pipe(switchMap((product) => { const requests = this.variantGroups.map((group) => group.value.id ? this.api.updateVariant(product.id, Number(group.value.id), this.toVariantRequest(group)) : this.api.createVariant(product.id, this.toVariantRequest(group))); return requests.length ? forkJoin(requests).pipe(switchMap(() => of(product))) : of(product); }), finalize(() => this.saving = false)).subscribe({ next: (product) => { if (!this.productId) { void this.router.navigate(['/products', product.id, 'edit']); } else { this.message = 'Product and variants saved.'; this.reloadProduct(); } }, error: (error: unknown) => this.error = apiMessage(error, 'Unable to save product.') }); }
  toggleVariant(group: FormGroup): void { if (!this.productId || !group.value.id) return; const active = !group.value.active; this.api.setVariantActive(this.productId, Number(group.value.id), active).subscribe({ next: () => group.patchValue({ active }), error: (error: unknown) => this.error = apiMessage(error, 'Unable to change variant status.') }); }
  private reloadProduct(): void { if (!this.productId) return; this.api.getVisible(this.productId).subscribe({ next: (product) => { this.product = product; this.variants.clear(); product.variants.forEach((variant) => this.variants.push(this.variantGroup(variant))); } }); }
}
